### ISSUE TITLE
Browser is still not happy.

### ISSUE THREAD

**Issue by annitya** [cognitedata/auth-wrapper#19]
![image](https://user-images.githubusercontent.com/727305/173397452-09a9465d-2920-4024-8d49-4b03e9701e35.png)
Seems like express-js is included into the mix. Browser is none too happy.

**Comment by devbarba** [comment]
Hey @annitya, thanks for report, we are already aware regarding it and working to have versions for react an node separated ASAP.

**Comment by BugGambit** [comment]
We are deprecating this package due to low usage.
